name: mapbox_turn_by_turn
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0-444.6.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # flutter_mapbox_navigation: ^0.0.26
  shared_preferences: ^2.0.13
  flutter_native_splash: ^2.0.4
  location: ^4.4.0
  google_fonts: ^2.3.1
  flutter_dotenv: ^5.0.2
  dio: ^4.0.4
  mapbox_gl: ^0.16.0
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.0
  flutter_plugin_android_lifecycle: ^2.0.7
  # navigation_with_mapbox: ^0.0.5
  navigation_with_mapbox: "0.0.1"
  flutter_map: ^0.14.0
  date_picker_timeline: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_native_splash:
  color: "#607D8B"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
